### ISSUE TITLE
light doesn't switch

### ISSUE THREAD

**Issue by Axterminator** [NordicPlayground/thingy52-mesh-provisioning-demo#1]
Main.c 
static bool on_off_server_set_cb(const generic_on_off_server_t * p_server, bool value)
{
   uint32_t err_code;
   __LOG(LOG_SRC_APP, LOG_LEVEL_INFO, "Got SET command to %u\n", value);
   if (value)
   {
       **ERROR_CHECK(drv_ext_light_on(1)); //was off**
       m_led_flag=1;
    }
    else
    {
      (void) drv_ext_light_off(1);
       m_led_flag=0;
    }
    
    return value;
}

**Comment by hubuhubu** [comment]
Thanks Axterminator . It's a mistake. Fixed now.
