### ISSUE TITLE
prebuild .hex does not match with build from src

### ISSUE THREAD

**Issue by Batov** [NordicPlayground/thingy52-mesh-provisioning-demo#2]
Hello,
First of all, thanks a lot for this public repo. It is very useful for explore and test Mesh with Thingy52.

But i have next issue:
1. I am working with [next commit](https://github.com/NordicPlayground/thingy52-mesh-provisioning-demo/commit/694521e141f81d288a957bbb3888037f76c67027). It is last _master_  branch commit.
2.  hex/Thingy52-mesh-provisioning-demo-v0.6.hex works perfectly. Mesh, provisioning, LED is OK.
3. I have build HEX from master ([step-by-step from here](https://github.com/NordicPlayground/thingy52-mesh-provisioning-demo#building-the-demo)) and flash to Thingy52. Mesh and provisioning is OK, but seems something wrong with LED. Seems that only first task (to IO-extender) for LED is working, but following tasks was skipped.
E.g.:
- Instead of double-blink LED blinks only once at start; 
- Before provisioning red blinking is OK but Output OOB blinking was skipped;

Could you please match _master_ with prebuild .hex?

**Comment by hubuhubu** [comment]
Hi Batov, 
I think LED blink once at start is normal operation (I'm not aware that it would blink twice)
When you do provisioning, please make sure you select output OOB when you provision. If you select no OOB, there will be no blink. If you can do provisioning without any input to the phone, that means it's either no OOB or static OOB.

**Comment by Batov** [comment]
Thanks for you answer!

I am using equal provisioning process (with output OOB) for devices with hex/Thingy52-mesh-provisioning-demo-v0.6.hex and compiled hex from source.

In my case I am using Segger RTT logs for specify output OOB result (because no blinks at LED).

Look at the [video](https://youtu.be/nkc7UGZZhWA)

**Comment by Batov** [comment]
Look at the [video](https://youtu.be/PamMyV4L1L0)
1. 4 devices at same mesh network
2. 3 devices flashed from pre-build hex
3. Last device started from source with j-link
4. Last device received message from another nodes
5. LED at last device is not working...

**Comment by Batov** [comment]
@hubuhubu Could you please me?

**Comment by Batov** [comment]
I have found issue reason.
Double to uint32_t casting is wrong. 
![image](https://user-images.githubusercontent.com/2099166/72248546-80fe2900-3608-11ea-946f-74d2c30e7d77.png)

In my case casting 0 double type to uint32_t type return 2 (!)

And optimal_time_settings_onoff_calculate at sx150x_led_drv_calc.c is not working correctly.
IMHO, something wrong with my setup of SES

**Comment by hubuhubu** [comment]
Thanks Batov, for future request, please use devzone to report issue.

**Comment by Batov** [comment]
Thanks. [Posted](https://devzone.nordicsemi.com/f/nordic-q-a/56540/thingy-52-mesh-example-at-segger-embedded-studio-issue).

**Comment by Batov** [comment]
Bug at SEGGER Embedded Studio for ARM Release 4.30c. Resolved.
